USE SUCOS_VENDAS;

SELECT * FROM NOTAS_FISCAIS;
SELECT * FROM ITENS_NOTAS_FISCAIS;
SELECT * FROM TABELA_FATURAMENTO;

DROP TRIGGER IF EXISTS TG_CALCULA_FATURAMENTO_INSERT;
DROP TRIGGER IF EXISTS TG_CALCULA_FATURAMENTO_UPDATE;
DROP TRIGGER IF EXISTS TG_CALCULA_FATURAMENTO_DELETE;

-- Versão UPDATE do gatilho
DROP TRIGGER IF EXISTS TG_CALCULA_FATURAMENTO_UPDATE;
DELIMITER //
CREATE TRIGGER IF NOT EXISTS TG_CALCULA_FATURAMENTO_UPDATE
    AFTER UPDATE
    ON ITENS_NOTAS_FISCAIS
    FOR EACH ROW
BEGIN
    DELETE FROM TABELA_FATURAMENTO;
    INSERT INTO TABELA_FATURAMENTO
    SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA
    FROM NOTAS_FISCAIS A
             INNER JOIN ITENS_NOTAS_FISCAIS B
                        ON A.NUMERO = B.NUMERO
    GROUP BY A.DATA_VENDA;
END;
//

-- Versão DELETE do gatilho
DROP TRIGGER IF EXISTS TG_CALCULA_FATURAMENTO_DELETE;
DELIMITER //
CREATE TRIGGER IF NOT EXISTS TG_CALCULA_FATURAMENTO_DELETE
    AFTER DELETE
    ON ITENS_NOTAS_FISCAIS
    FOR EACH ROW
BEGIN
    DELETE FROM TABELA_FATURAMENTO;
    INSERT INTO TABELA_FATURAMENTO
    SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA
    FROM NOTAS_FISCAIS A
             INNER JOIN ITENS_NOTAS_FISCAIS B
                        ON A.NUMERO = B.NUMERO
    GROUP BY A.DATA_VENDA;
END;
//
