DROP DATABASE IF EXISTS SUCOS_VENDAS;
CREATE DATABASE SUCOS_VENDAS;

DROP TABLE IF EXISTS [TABELA DE CLIENTES];
DROP TABLE IF EXISTS [TABELA DE PRODUTOS];
DROP TABLE IF EXISTS [TABELA DE VENDEDORES];

CREATE TABLE [TABELA DE CLIENTE]
(

    [CPF]                [CHAR](11) NOT NULL PRIMARY KEY,
    [NOME]               [VARCHAR](150),
    [RUA]                [VARCHAR](150),
    [COMPLEMENTO]        [VARCHAR](150),
    [BAIRRO]             [VARCHAR](150),
    [ESTADO]             [VARCHAR](150),
    [CEP]                [CHAR](8),
    [DATA DE NASCIMENTO] [DATE],
    [IDADE][SMALLINT],
    [SEXO]               [CHAR](1),
    [LIMITE DE CREDITO]  [MONEY],
    [PRIMEIRA COMPRA]    [BIT]
);

CREATE TABLE [TABELA DE PRODUTOS]
(

    [CODIGO DE PRODUTO][VARCHAR](20) PRIMARY KEY,
    [NOME DO PRODUTO][VARCHAR](50),
    [EMBALAGEM][VARCHAR](50),
    [TAMANHO][VARCHAR](50),
    [SABOR][VARCHAR](50),
    [PRECO DE LISTA][SMALLMONEY],
);

CREATE TABLE [TABELA DE VENDEDORES]
(
    [MATRICULA]           varchar(5) NOT NULL PRIMARY KEY,
    [NOME]                varchar(100),
    [PERCENTUAL COMISSAO] float
);
 