--DROP DATABASE IF EXISTS [VENDAS SUCOS];
--CREATE DATABASE [VENDAS SUCOS];

--DROP TABLE IF EXISTS PRODUTOS;
--DROP TABLE IF EXISTS VENDEDORES;
--DROP TABLE IF EXISTS CLIENTES;
--DROP TABLE IF EXISTS TABELA_DE_VENDAS;
--DROP TABLE IF EXISTS TABELA_DE_ITENS_VENDIDOS;

CREATE TABLE PRODUTOS
(
    CODIGO      VARCHAR(10)  NOT NULL,
    DESCRITOR   VARCHAR(100) NULL,
    SABOR       VARCHAR(50)  NULL,
    TAMANHO     VARCHAR(50)  NULL,
    EMBALAGEM   VARCHAR(50)  NULL,
    PRECO_LISTA FLOAT        NULL,

    PRIMARY KEY (CODIGO)
);

CREATE TABLE VENDEDORES
(
    MATRICULA     VARCHAR(5)   NOT NULL,
    NOME          VARCHAR(100) NULL,
    BAIRRO        VARCHAR(50)  NULL,
    COMISSAO      FLOAT        NULL,
    DATA_ADMISSAO DATE         NULL,
    FERIAS        BIT          NULL,

    PRIMARY KEY (MATRICULA)
);

CREATE TABLE CLIENTES
(
    CPF             VARCHAR(11)  NOT NULL,
    NOME            VARCHAR(100) NULL,
    ENREDECO        VARCHAR(100) NULL,
    BAIRRO          VARCHAR(50)  NULL,
    CIDADE          VARCHAR(50)  NULL,
    ESTADO          VARCHAR(50)  NULL,
    CEP             VARCHAR(8)   NULL,
    DATA_NASCIMENTO DATE         NULL,
    IDADE           INTEGER      NULL,
    GENERO          VARCHAR(1)   NULL,
    LIMITE_CREDITO  FLOAT,
    VOLUME_COMPRA   FLOAT,
    PRIMAIRA_COMPRA BIT,
    PRIMARY KEY (CPF)
);

CREATE TABLE TABELA_DE_VENDAS
(
    NUMERO     VARCHAR(5)  NOT NULL,
    DATA_VENDA DATE        NULL,
    CPF        VARCHAR(11) NOT NULL,
    MATRICULA  VARCHAR(5)  NOT NULL,
    IMPOSTO    FLOAT       NULL,
    PRIMARY KEY (NUMERO),
    FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF),
    FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA)
);


CREATE TABLE TABELA_DE_ITENS_VENDIDOS
(
    NUMERO     VARCHAR(5)  NOT NULL,
    CODIGO     VARCHAR(10) NOT NULL,
    QUANTIDADE FLOAT       NULL,
    PRECO      FLOAT       NULL,
    PRIMARY KEY (NUMERO, CODIGO),
    FOREIGN KEY (NUMERO) REFERENCES TABELA_DE_VENDAS (NUMERO)
);

INSERT INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES ('1040107', 'Light - 350 ml - Melancia', 'Melancia', '350 ml', 'Lata', 4.56),
       ('1040108', 'Light - 350 ml - Graviola', '   Graviola', '350 ml', 'Lata', 4.00),
       ('1040109', 'Light - 350 ml - Açai', 'Açai', '350 ml', 'Lata', 5.60),
       ('1040110', 'Light - 350 ml - Jaca', 'Jaca', '350 ml', 'Lata', 3.50),
       ('1040111', 'Light - 350 ml - Manga', 'Manga', '350 ml', 'Lata', 3.20),
       ('1040112', 'Light - 350 ml - Maça', 'Maça', '350 ml', 'Lata', 4.20);

SELECT *
FROM PRODUTOS;


INSERT INTO CLIENTES (CPF, NOME, ENREDECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_NASCIMENTO, IDADE, GENERO, LIMITE_CREDITO,
                      VOLUME_COMPRA, PRIMAIRA_COMPRA)
VALUES ('1471156710', 'Érica Carvalho', 'R. Iriquitia', '', 'Jardins', 'São Paulo', 'SP', '1990-09-01', 27, 'F', 170000,
        24500, 0),
       ('19290992743', 'Fernando Cavalcante', 'R. Dois de Fevereiro', '', 'Água Santa', 'Rio de Janeiro', 'RJ',
        '2000-02-12', 18, 'M', 100000, 20000, 1),
       ('2600586709', 'César Teixeira', 'Rua Conde de Bonfim', '', 'Tijuca', 'Rio de Janeiro', 'RJ', '2000-03-12', 18,
        'M', 120000, 22000, 0);

SELECT *
FROM CLIENTES;