CREATE VIEW VW_QUANTIDADE_PRODUTOS AS
SELECT INF.CODIGO_DO_PRODUTO,
       TP.NOME_DO_PRODUTO,
       SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM ITENS_NOTAS_FISCAIS INF
         INNER JOIN TABELA_DE_PRODUTOS TP
                    ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO;
